# For more info on HTTP files go to https://aka.ms/vs/httpfile
POST http://localhost:7236/api/MakeCategory
Content-Type: application/json

{
    "Category" : "CATEGORY1"
}

###
POST http://localhost:7236/api/MakeCategory
Content-Type: application/json

{
    "Category" : "category2"
}